version: "3.8"

name: billionaires-dashboard

volumes:
  bd_postgres_data:

services:
  backend:
    container_name: bd-backend-dev
    extends:
      file: docker-compose.base.yml
      service: backend
    build:
      target: dev
    env_file:
      - ./backend/.env.dev
    develop:
      watch:
        - action: rebuild
          path: backend/package.json
        - action: sync
          path: backend/src
          target: /app/src
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: bd-db-dev
    extends:
      file: docker-compose.base.yml
      service: db

  frontend:
    container_name: bd-frontend-dev
    extends:
      file: docker-compose.base.yml
      service: frontend
    build:
      target: dev
    develop:
      watch:
        - action: rebuild
          path: frontend/package.json
        - action: sync+restart
          path: frontend/vite.config.ts
          target: /app/vite.config.ts
        - action: sync
          path: frontend/src
          target: /app/src
        - action: sync
          path: frontend/index.html
          target: /app/index.html
    environment:
      - VITE_BACKEND_URL=http://localhost:3000/
