- hosts: all
  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # one day
  roles:
    - role: geerlingguy.postgresql
      become: yes
